Merge branch 'merge_cosmicfish'
santiagocasas/cosmicfishpie pull request #35
Opened 2024-04-18 23:09 UTC by Sefa76

Changes proposed in this pull request:
Merged remote cosmicfish repo into cosmicfishpie
        Mainly changes to the plotting routine
        Added new external file for nonlinear power spectra
        New options for spectroscopic error. Removed infamous h-bug

2024-06-26 13:11 UTC, Sefa76 commented
This has now the newest additions to cosmicfish.
- Fishconsumer module 
- additional option to add your own colors to the plotting routines

This also fixes old problems
- Removed any deprecated functions with slur-adjacent names
- Toned down the printing when plotting fishers

2024-07-08 10:05 UTC, santiagocasas requested changes
Address the little changes of the bug and that should be all fine! thanks!

2024-07-08 10:05 UTC, santiagocasas commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +            k = self.k_units_change(k)  # has to be done before spec_err and AP
Leave also a comment here....

2024-07-08 10:57 UTC, Sefa76 commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +        self.kh_rescaling_beforespecerr = cfg.specs["spec_khrescale_beforespecerr"]
After looking at it a bit longer i dont thin its a good idea to have the bug in the survey specifications
I would rather have it in options

2024-07-08 12:57 UTC, santiagocasas requested changes
thanks for the changes, after fixing the typos, this should be all good!

2024-07-08 12:57 UTC, santiagocasas commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +        The code is defined everzwhere in 1/Mpc so a rescaling would be wwrong.
a typo here in z/y

2024-07-08 12:57 UTC, santiagocasas commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +        self.kh_rescaling_beforespecerr_bug = cfg.settings["kh_rescaling_beforespecerr_bug"]
ok, agree with having this in specs, you are right!

2024-07-08 12:57 UTC, santiagocasas commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +                category=RuntimeWarning,
nice!

2024-07-08 12:57 UTC, santiagocasas commented on cosmicfishpie/LSSsurvey/spectro_obs.py
> +            # In this case the the h-bug is only applied before computing the resolution supressuion
typo: suppression

2024-07-08 14:14 UTC, santiagocasas approved these changes
Good!

2024-07-08 14:15 UTC, merged

2024-07-08 14:20 UTC, santiagocasas commented
well done!